version: "4.5"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: array
      MYSQL_USER: user
      MYSQL_PASSWORD: db_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports: 
      - 3307:3306
    expose:
      - 3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  app:
    container_name: array
    image: array
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_DATABASE: array
      DB_USER: user
      DB_PASSWORD: db_password
      DB_HOSTNAME: db

volumes:
  my-db: